### PR TITLE
permalinks documentation

### PR DESCRIPTION
**Pull request by dperrera**
This is a first pass at some documentation for permalinks. I didn't see an existing page where it fit in neatly so I added a new one after configuration that hopefully builds on concepts that will be used in the following sections. 

I'm new to contributing to OSS, so let me know if I can do anything better.

### CODE REVIEW

**Comment by hswolff** [comment]
Awesome! So much appreciated! I'm gonna make a few tweaks and then deploy it!

**Comment by hswolff** [comment]
It's live! http://reptar.github.io/docs/permalinks/

**Comment by dperrera** [comment]
That's great! 

I don't know if you're interested, but I'd love to be more involved with Reptar. I'm a designer/ front-ender and am trying to get more into Node and open source. I'd love to see this project take off so if there's anything I can do in terms of branding or design, I'd be happy to help. I'd be excited to contribute to the core project as well if you can put up with my questions. I don't want to be an open source burden, so let me know what you think.

**Comment by hswolff** [comment]
Hey @dperrera I would love your help! Happy to see you get involved with either more core work in Reptar or right now I'm starting work on a reptar-dashboard that is just getting off the ground. 

Also if you have any ideas for a better layout for the docs page those are welcome as well.

Feel free to ping me whenever - here, on twitter, or in Gitter. https://gitter.im/reptar/Lobby

**Pull request merged**
